# Generated by Django 6.0.3 on 2026-03-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_mappings', to='product.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='vendor.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'is_active'], name='vendor_prod_vendor__4d040b_idx'), models.Index(fields=['product', 'is_active'], name='vendor_prod_product_a02719_idx')],
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
