# Generated by Django 6.0.3 on 2026-03-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCourseMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_mappings', to='course.course')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mappings', to='product.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='product_cou_product_60e910_idx'), models.Index(fields=['course', 'is_active'], name='product_cou_course__de2df0_idx')],
                'unique_together': {('product', 'course')},
            },
        ),
    ]
